accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name="followers")

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="likearticles")
    title = models.CharField(max_length=10)         #나중에 지우기
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# from django.contrib.auth import login as auth_login, logout as auth_logout
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm, 
    UserCreationForm, 
    PasswordChangeForm,
)
from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person' : person,
    }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, username):
    if request.user.is_authenticated:
        you = get_object_or_404(get_user_model(), username=username)
        me = request.user
        if you != me:
            if you.followers.filter(username=me.username).exists():
                you.followers.remove(me)
            else:
                you.followers.add(me)
        return redirect('accounts:profile', you.username)
    return redirect('accounts:login')
    

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호변경</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="container" style="width:1000px">

    <!--프로필 상단부분-->
    <div class="container mt-4" style="height:200px">
      <div class="row h-100">
        <div class="col-4">
          <!--프로필사진-->
          profile photo
        </div>
        <div class="col-8 d-flex flex-column">
          <div class="d-flex mt-3">
            <div class="h3">{{ person.username}}</div>
            <div class="btn btn-light ms-4">프로필 편집</div>
            <!--아이콘에 버튼기능 추가해야함 -->
            <div class="ms-3 d-flex align-items-center"><i class="fas fa-cog" style="color:	#646464"></i></div>
          </div>
          <div class="d-flex mt-3">
            <div class="me-5">게시글 {{ person.article_set.all|length}}</div>
            <div class="me-5">팔로워 {{ person.followers.all|length}}</div>
            <div class="me-5">팔로우 {{ person.followings.all|length}}</div>
          </div>
          <div class="mt-3 fw-bold">소개글 입력 받는거 추가해야함</div>
        </div>
      </div>
    </div>
    <hr>

    <!--가운데 버튼 바-->
    <div style="height:45px">
      <a href="{% url 'accounts:profile' person.username %}" class="text-decoration-none text-dark"><i class="fas fa-grip-horizontal" style="color: #646464"></i>  게시물</a>
      <a href="{% url 'accounts:profile' person.username %}" class="text-decoration-none text-dark"><i class="fas fa-grip-horizontal" style="color: #646464"></i>  게시물</a>
    </div>

    <!--아래 사진들 카드형식으로 보여주기-->
    <div class="row row-cols-3 g-4">
      {% for article in person.article_set.all %}
        <div class="col">
          <div class="card h-100">
            {% comment %} <a href="{% url 'articles:detail' article.pk %}">
              <img src="{{article.image.url}}" alt="">
            </a> {% endcomment %}
            <img src="{{article.image.url}}" alt="">
          </div>
        </div>
      {% endfor %}
    </div>
    



    <!--여기부터-->
    {% comment %} {% if request.user != person %}
      <form action="{% url 'accounts:follow' person.username %}" method="POST">
        {% csrf_token %}
        {% if request.user in person.followers.all %}
          <button>언팔로우</button>
        {% else %}
          <button>팔로우</button>
        {% endif %}
      </form>
    
    {% endif %}

    <hr>
    <h3>게시글</h3>
    {% for article in person.article_set.all %}
      <p>번호 : {{ article.pk }}</p>
      <p>제목 : {{ article.title }}</p>
      <p>내용 : {{ article.content}}</p>
      <hr>
    {% endfor %}
    
    <h3>댓글</h3>
    {% for comment in person.comment_set.all %}
      {{ article.comment }}
      <hr>
    {% endfor %}
    <hr>
    <h3>좋아요한 게시글</h3>
    <p><i class="fas fa-heart" style="crimson"></i>지금까지 {{ person.likearticles.all|length }}개의 글을 좋아합니다.</p>
    {% for article in person.likearticles.all %}
      {{ article.pk }} - {{ article.title }}
      <hr>
    {% endfor %} {% endcomment %}
  </div>
{% endblock content %}


<!--혹시몰라서 복붙해놓음-->
{% comment %} 
{% extends 'base.html' %}
{% block content %}
  <h1>{{ person.username }}님의 프로필</h1>

  <h4>팔로워 : {{ person.followers.all|length }}  팔로잉 : {{ person.followings.all|length }}</h4>

  {% if request.user != person %}
    <form action="{% url 'accounts:follow' person.username %}" method="POST">
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <button>언팔로우</button>
      {% else %}
        <button>팔로우</button>
      {% endif %}
    </form>
  
  {% endif %}

  <hr>
  <h3>게시글</h3>
  {% for article in person.article_set.all %}
    <p>번호 : {{ article.pk }}</p>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content}}</p>
    <hr>
  {% endfor %}
  
  <h3>댓글</h3>
  {% for comment in person.comment_set.all %}
    {{ article.comment }}
    <hr>
  {% endfor %}
  <hr>
  <h3>좋아요한 게시글</h3>
  <p><i class="fas fa-heart" style="crimson"></i>지금까지 {{ person.likearticles.all|length }}개의 글을 좋아합니다.</p>
  {% for article in person.likearticles.all %}
    {{ article.pk }} - {{ article.title }}
    <hr>
  {% endfor %}
{% endblock content %} {% endcomment %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>회원정보수정</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}